package com.example.transactionalsystemjavavue.domain;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Domain kernel for "Procesamiento de Saga para Creación de Pedidos en Java Spring Boot" (generated by gherkin-ai).
 * Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
 */
public class ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootAggregate {
    private final String id;
    private ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootState state = ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootState.PENDING;
    private long version;
    private final List<ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootDomainEvent> pendingEvents = new ArrayList<>();

    public ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootAggregate(String id) {
        if (id == null || id.isBlank()) throw new DomainValidationException("ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBoot id is required");
        this.id = id;
    }

    public String getId() { return id; }
    public ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootState getState() { return state; }
    public long getVersion() { return version; }

    /** Events recorded since the aggregate was loaded (to be saved via the outbox). */
    public List<ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootDomainEvent> getPendingEvents() { return Collections.unmodifiableList(pendingEvents); }

    public ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootDomainEvent createOrder(ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootCommand command) {
        assertValid(command);
        return record(ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootEventType.Orderoutboxevents, command.payload());
    }

    private void assertValid(ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootCommand command) {
        if (command == null || command.id() == null || command.id().isBlank()) throw new DomainValidationException("Command id is required");
        if (!command.id().equals(id)) throw new DomainValidationException("Command targets " + command.id() + ", not " + id);
    }

    private ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootDomainEvent record(ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootEventType type, Map<String, Object> payload) {
        version += 1;
        var event = new ProcesamientoDeSagaParaCreacionDePedidosEnJavaSpringBootDomainEvent(type, id, version, Instant.now(), payload == null ? Map.of() : payload);
        pendingEvents.add(event);
        return event;
    }
}
